# Generated by Django 4.0.4 on 2022-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Customer`s Name')),
                ('phone', models.CharField(max_length=13, verbose_name='Customer`s Phone Number')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Customer`s Paid Fee')),
                ('remaining_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Customer`s Remaining Fee')),
                ('month', models.DateField(auto_now_add=True, verbose_name='Fee of the Month')),
                ('given_on_date', models.DateTimeField(auto_now_add=True, verbose_name='Fee`s Date')),
            ],
        ),
    ]
