# Generated by Django 4.0.4 on 2022-05-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=265, verbose_name='Area Name')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=4, verbose_name='Customer`s ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Customer`s Name')),
                ('phone', models.CharField(max_length=13, verbose_name='Customer`s Phone Number')),
                ('address', models.TextField(verbose_name='Customer`s Address')),
                ('customer_status', models.CharField(choices=[('Active', 'active'), ('Disabled', 'disabled')], default='disabled', max_length=10)),
                ('customer_fee_assigned', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Customer`s Assigned Fee')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='main.area', verbose_name='Customer`s area')),
            ],
        ),
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subarea_name', models.CharField(max_length=256, verbose_name='Sub-Area`s Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerarea', to='main.area', verbose_name='Main area')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20000, verbose_name='Shop Name')),
                ('shop_contact', models.TextField(verbose_name='Shop Contact Information')),
                ('shop_details', models.TextField(verbose_name='Shop Location/Adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopholder', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Customer`s Paid Fee')),
                ('fee_status', models.CharField(choices=[('Paid', 'paid'), ('Not Paid', 'not_paid')], default='not_paid', max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Customer`s Debit Fee')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Customer`s Debit Fee')),
                ('month', models.DateField(verbose_name='Fee of the Month')),
                ('given_on_date', models.DateTimeField(auto_now_add=True, verbose_name='Fee`s Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='main.customers')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='assigned_to_subuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customersubuser', to='main.subuser'),
        ),
        migrations.AddField(
            model_name='customers',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sarea', to='main.subarea', verbose_name='Customer`s Sub-Area'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='area_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subname', to='main.subuser'),
        ),
    ]
