# Generated by Django 4.0.4 on 2022-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(max_length=4, unique=True, verbose_name='Customer`s ID'),
        ),
    ]
