# Generated by Django 4.0.4 on 2022-04-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customers_fee_alter_customers_remaining_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='given_on_date',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='month',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='remaining_fee',
        ),
        migrations.AddField(
            model_name='customers',
            name='cnic',
            field=models.CharField(default=1, max_length=15, verbose_name='Customer`s CNIC'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Customer`s Paid Fee')),
                ('remaining_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Customer`s Remaining Fee')),
                ('month', models.DateField(auto_now_add=True, verbose_name='Fee of the Month')),
                ('given_on_date', models.DateTimeField(auto_now_add=True, verbose_name='Fee`s Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='main.customers')),
            ],
        ),
    ]
