# Generated by Django 4.0.4 on 2022-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customers_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Customer`s ID'),
        ),
    ]
