# Generated by Django 4.0.4 on 2022-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customers_fee_remove_customers_given_on_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.DateField(verbose_name='Fee of the Month'),
        ),
    ]
