# Generated by Django 4.0.4 on 2022-05-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=265, unique=True, verbose_name='Area Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subname', to='main.subuser', unique=True),
        ),
    ]
