# Generated by Django 3.2.8 on 2022-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_area_area_name_alter_area_area_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
