# Generated by Django 3.2.8 on 2022-05-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Not Paid', 'not_paid')], default='Not Paid', max_length=10),
        ),
    ]
