# Generated by Django 3.2.8 on 2022-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fee_fee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='month',
        ),
        migrations.AddField(
            model_name='fee',
            name='Date',
            field=models.DateField(verbose_name='Fee of the Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='Month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
