# Generated by Django 3.2.8 on 2022-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220512_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
