# Generated by Django 3.2.8 on 2022-05-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220512_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
