# Generated by Django 3.2.8 on 2022-05-12 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_fee_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Added BY Admin user'),
        ),
    ]
