# Generated by Django 4.0.4 on 2022-05-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=265, verbose_name='Area Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subname', to='main.subuser'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer`s Address'),
        ),
    ]
